name: all
on:
  workflow_call:
    secrets:
      DOPPLER_TOKEN:
        required: true
      TF_CLOUD_TOKEN:
        required: false
        default: ""
jobs:
  test:
    uses: ./terraform/test.yml
    secrets:
      TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
  build:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: test
    uses: ./terraform/apply.yml
    secrets:
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
  post_build:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: 
      - test
      - build
    uses: ./terraform/docs.yml

  