name: docker-lint

on:
  workflow_call:
    inputs:
      dockerfile:
        required: false
        type: string
        default: "Dockerfile"

jobs:
  lint-docker:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run lint
        uses: ghe-actions/dockerfile-validator@v1
        with:
          dockerfile: ${{ inputs.Dockerfile }}
          lint: 'hadolint'