eiifccuhdutflnttnnkvrtvename: terraform-validate
on:
  workflow_call:
    secrets:
      TF_CLOUD_TOKEN:
        required: false
jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      - name: Check token set
        id: token-check
        # perform secret check & put boolean result as an output
        shell: bash
        run: |
          if [ "${{ secrets.TF_CLOUD_TOKEN }}" != '' ]; then
            echo "token_set=true" >> $GITHUB_OUTPUT;
          else
            echo "token_set=false" >> $GITHUB_OUTPUT;
          fi
      - name: Terraform Init with token
        if: ${{ steps.secret-check.outputs.token_set == 'true' }}
        shell: bash
        run: printenv && terraform init
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_CLOUD_TOKEN }}
      - name: Terraform Init
        if: ${{ steps.secret-check.outputs.token_set != 'true' }}
        shell: bash
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
