name: terraform-apply
on:
  workflow_call:
    secrets:
      DOPPLER_TOKEN:
        required: false
      TF_CLOUD_TOKEN:
        required: false
jobs:
  apply:
    name: deploy to terraform cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Check token set
        id: token-check
        # perform secret check & put boolean result as an output
        shell: bash
        run: |
          if [ "${{ secrets.TF_CLOUD_TOKEN }}" != '' ]; then
            echo "token_set=true" >> $GITHUB_OUTPUT;
          else
            echo "token_set=false" >> $GITHUB_OUTPUT;
          fi
      - name: Terraform apply with token
        if: ${{ steps.token-check.outputs.token_set == 'true' }}
        shell: bash
        run: |
          terraform init
          terraform plan -input=false -no-color -out planfile
          terraform apply -input=false -no-color -auto-approve planfile
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_CLOUD_TOKEN }}
          TF_VAR_doppler_token: ${{ secrets.DOPPLER_TOKEN }}
      - name: Terraform apply
        if: ${{ steps.token-check.outputs.token_set != 'true' }}
        shell: bash
        run: |
          terraform init
          terraform plan -input=false -no-color -out planfile
          terraform apply -input=false -no-color -auto-approve planfile
        env:
          TF_VAR_doppler_token: ${{ secrets.DOPPLER_TOKEN }}