name: terraform-test
on:
  workflow_call:
    secrets:
      TF_CLOUD_TOKEN:
        required: false
        default: ""
jobs:
  lint:
    uses: ./.github/workflows/terraform-lint.yml
  validate:
    uses: ./.github/workflows/terraform-validate.yml
    secrets:
      TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
